Date & time        : 8/18/2020   12:33 PM
Operator           : YHu
EUT                : Punkl_4
Reference          : 

Comment


Monitoring system

   Channel 1       : Isotrope
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_pionowo
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_wzduz
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 4       : Ex_poprzecznie
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 5       : Probe temp
   Unit            : Sensor Temp °C
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : GEN_Output
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch4	       Ch5	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       V/m	Sensor Tem	       dBm	

   80.000000	 4.9832E+0	 5.1060E+0	 4.9538E+0	 1.0298E+0	803.5930E-3	37.3121E+0	-4.8000E+0	   0000000
   80.800000	 4.7877E+0	 4.9202E+0	 4.7907E+0	960.6810E-3	763.3350E-3	37.3143E+0	-4.9900E+0	   0000000

   