Date & time        : 8/17/2020   5:53 PM
Operator           : YHu
EUT                : Punkl_2
Reference          : 

Comment


Monitoring system

   Channel 1       : Ex_Primary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : GTEM Input
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       dBm	

   80.000000	 5.0312E+0	 4.9817E+0	 1.1968E+0	377.0810E-3	-8.2000E+0	     00000
   80.800000	 4.8421E+0	 4.8140E+0	 1.1900E+0	363.4470E-3	-8.4200E+0	     00000

  