Date & time        : 8/17/2020   5:06 PM
Operator           : YHu
EUT                : Punkl_1
Reference          : 

Comment


Monitoring system

   Channel 1       : Ex_Primary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 4       : Isotrop
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : GTEM Input
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch4	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       V/m	       dBm	

   80.000000	 5.0370E+0	 4.9747E+0	889.5160E-3	 1.0488E+0	 5.1632E+0	-8.4300E+0	    000000
   80.800000	 4.8613E+0	 4.8416E+0	889.2860E-3	996.5990E-3	 5.0184E+0	-8.6400E+0	    000000


