Date & time        : 8/18/2020   12:58 PM
Operator           : YHu
EUT                : Punkl_5
Reference          : 

Comment


Monitoring system

   Channel 1       : Isotrope
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_pionowo
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_wzduz
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 4       : Ex_poprzecznie
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 5       : Probe temp
   Unit            : Sensor Temp °C
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : Dir_Coupler_For
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch4	       Ch5	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       V/m	Sensor Tem	       dBm	

   80.000000	 5.0129E+0	 5.0643E+0	 4.9680E+0	844.8510E-3	498.9150E-3	35.6081E+0	-6.3500E+0	   0000000
   80.800000	 4.8030E+0	 4.8858E+0	 4.7808E+0	827.9900E-3	489.1610E-3	35.6417E+0	-6.5400E+0	   0000000
 