Date & time        : 8/17/2020   5:53 PM
Operator           : YHu
EUT                : Punkl_2
Reference          : 

Comment


Monitoring system

   Channel 1       : Ex_Primary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : GTEM Input
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       dBm	

   80.000000	 5.0312E+0	 4.9817E+0	 1.1968E+0	377.0810E-3	-8.2000E+0	     00000
   80.800000	 4.8421E+0	 4.8140E+0	 1.1900E+0	363.4470E-3	-8.4200E+0	     00000
   81.608000	 5.0225E+0	 4.9777E+0	 1.2683E+0	376.6030E-3	-8.0500E+0	     00000
   82.424080	 4.8826E+0	 4.8925E+0	 1.2522E+0	363.4500E-3	-8.2300E+0	     00000
   83.248321	 4.8676E+0	 4.8631E+0	 1.2557E+0	360.2350E-3	-8.2600E+0	     00000
   84.080804	 4.8946E+0	 4.8835E+0	 1.2482E+0	352.3030E-3	-8.2900E+0	     00000
   84.921612	 4.9712E+0	 4.9779E+0	 1.2670E+0	345.3450E-3	-8.1000E+0	     00000
   85.770828	 5.0862E+0	 5.1079E+0	 1.3011E+0	338.5560E-3	-7.8800E+0	     00000
   86.628536	 5.1798E+0	 5.1424E+0	 1.3180E+0	325.5360E-3	-7.5700E+0	     00000
   87.494822	 5.2036E+0	 5.2048E+0	 1.3471E+0	326.3330E-3	-7.1600E+0	     00000
  