Date & time        : 8/18/2020   11:29 AM
Operator           : YHu
EUT                : Punkl_3
Reference          : 

Comment


Monitoring system

   Channel 1       : Ex_Primary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 2       : Ey_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 3       : Ez_Secondary
   Unit            : V/m
   Instrument      : LSProbe 1.2
   Data file       : 
   Limits          : no evaluation

   Channel 6       : GEN_Output
   Unit            : dBm
   Instrument      : NSG4070-45 9.6kBaud
   Data file       : NSG4070_CH1.DAT
   Limits          : no evaluation

Frequencies
   Start           : 80.000000 MHz
   Stop            : 1000.000000 MHz
   Step            : 1.000000 %

Reference input
   Fix value       : 5.0 V/m
   Offset          : 0.0 V/m
   Dwell time      : 0.5 s

Control system
   Loop            : closed
   Ctrl. conditions
     Tolerance     : 0.50 dB

Settings of signal generation
   Device          : NSG4070-45 9.6kBaud
   RF ON/OFF       : ON
   MOD ON/OFF      : OFF

   Range  1        :      0.010000 ...  1000.000000 MHz

Settings of signal coupling
   Device          : GTEM1500

   Part 1          :     80.000000 ...  1000.000000 MHz

Results of part(s)  1

     Frequ	        RV	       Ch1	       Ch2	       Ch3	       Ch6	    Status
       MHz	       V/m	       V/m	       V/m	       V/m	       dBm	

   80.000000	 5.0270E+0	 5.0014E+0	 1.1485E+0	 1.8371E+0	-8.1400E+0	     00000
   80.800000	 4.8324E+0	 4.8098E+0	 1.1443E+0	 1.7529E+0	-8.3200E+0	     00000
   81.608000	 4.9706E+0	 4.9892E+0	 1.2001E+0	 1.8015E+0	-7.9800E+0	     00000
   82.424080	 4.8548E+0	 4.8317E+0	 1.1878E+0	 1.7274E+0	-8.1300E+0	     00000
   83.248321	 4.8131E+0	 4.7996E+0	 1.1914E+0	 1.6846E+0	-8.1600E+0	     00000
   84.080804	 4.7913E+0	 4.7906E+0	 1.1758E+0	 1.6582E+0	-8.1900E+0	     00000
   84.921612	 4.8661E+0	 4.8752E+0	 1.2009E+0	 1.6533E+0	-8.0000E+0	     00000
   85.770828	 4.9451E+0	 4.9471E+0	 1.2190E+0	 1.6661E+0	-7.7500E+0	     00000
   86.628536	 5.0188E+0	 5.0190E+0	 1.2482E+0	 1.6726E+0	-7.4700E+0	     00000
   87.494822	 5.0492E+0	 5.0460E+0	 1.2629E+0	 1.7204E+0	-7.0600E+0	     00000
  